server:
  port: 8080
  mode: "debug"

db:
  driver: "postgres"
  host: "localhost"
  port: 5432
  name: "aifriends"
  sslmode: "disable"
  
log:
  level: "debug"
  filename: "./log/aifriends.log"
  max_size: 200
  max_age: 30
  max_backups: 7

cors:
  allow_origins:
    - "http://localhost:5173"
  allow_credentials: true
