server:
  port: 8080
  mode: "debug"

db:
  driver: "postgres"
  host: "localhost"
  port: 5432
  name: "aifriends"
  sslmode: "disable"
  time_zone: "Asia/Shanghai"

redis:
  host: "127.0.0.1"
  port: 16379
  password: ""
  db: 0
  pool_size: 100
  
log:
  level: "debug"
  filename: "./log/aifriends.log"
  max_size: 200
  max_age: 30
  max_backups: 7

jwt: 
  access_exp: 7200
  refresh_exp: 604800

cors:
  allow_origins:
    - "http://localhost:5173"
    - "http://127.0.0.1:5173"
  allow_credentials: true
